import type { NextPage } from 'next'
import Head from 'next/head'

// TODO: Make a test page with all the components for style change testing
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mcnuggies.ico" />
      </Head>

      <main>
        <h1>
          Heading 1
        </h1>
        <h2>
          Heading 2
        </h2>
      </main>
    </div>
  )
}

export default Home
