name: web-cypress-tests
on: [push]
jobs:
  web-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          working-directory: web
        # see https://docs.github.com/en/actions/security-guides/encrypted-secrets
        env:
          SANITY_PROJECT: ${{ secrets.SANITY_PROJECT }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          NODE_ENV: 'production'