name: web-cypress-tests
on: [push]
jobs:
  web-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Workaround step so we have control over the cache in the GH action
      # since there is currently no way to clear the cache between runs
      # see: https://github.community/t/how-to-clear-cache-in-github-actions/129038
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            /usr/local/bin/yarn
          key: ${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/lockfiles') }}
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn serve
          working-directory: web
        # see https://docs.github.com/en/actions/security-guides/encrypted-secrets
        env:
          SANITY_PROJECT: ${{ secrets.SANITY_PROJECT }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          NODE_ENV: 'production'